FROM node:18 as development

ENV NODE_VERSION 18.4.0

WORKDIR /usr/src/app

COPY package.json ./
COPY yarn.lock ./

RUN yarn add glob rimraf -D

RUN yarn

COPY . .

RUN yarn build

FROM node:18 as production

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}
ENV NODE_VERSION 18.4.0

WORKDIR /usr/src/app

COPY package*.json ./
COPY yarn.lock ./

RUN yarn

COPY . .

RUN yarn build

CMD ["node", "dist/server/src/main"]
