version: "3.8"

services:
    postgres:
        container_name: postgres
        image: postgres:14.4
        #DATABASE_URL="postgresql://postgres:1234@localhost:5432/tabledb?schema=public"
        environment:
            - POSTGRES_PASSWORD=1234
            - POSTGRES_USER=postgres
            - POSTGRES_DB=tabledb
        ports:
          - 5432:5432   
        networks:
            - nestjs-network
        restart: always
        volumes:
            - postgres:/var/lib/postgresql/data
    dev:
        container_name: nestjs_api_dev
        image: nestjs-api-dev:1.0.0
        build:
            context: .
            target: development
            dockerfile: ./DOCKERFILE
        depends_on:
            - postgres
        command: npm run start:debug
        ports:
            - 3000:3000
            - 9229:9229
            - 3010:3010
        networks:
            - nestjs-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: on-failure
    prod:
        container_name: nestjs_api_prod
        image: nestjs-api-prod:1.0.0
        build:
            context: .
            target: production
            dockerfile: ./DOCKERFILE
        depends_on:
            - postgres
        command: npm run start:prod
        ports:
            - 3000:3000
            - 9229:9229
        networks:
            - nestjs-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: on-failure

networks:
    nestjs-network:
volumes:
  postgres:
    name: nest-db
